"""LinkedIn-game historical backfill parsing and saving. (Minigames cog impl mixin; see minigames.py)."""

import datetime as dt
import json
import logging
from types import SimpleNamespace


from tle.util import codeforces_common as cf_common

from tle.cogs._minigame_queens import (
    normalize_queens_name,
)
from tle.cogs._minigame_helpers import (
    MinigameCogError,
)
from tle.cogs._minigame_queens_cog import (
    _QueensResolvedEntry, _QueensBackfillResult, _QUEENS_BACKFILL_MAX_BYTES,
    _queens_puzzle_date_text,
)

logger = logging.getLogger(__name__)


class ImplQueensBackfillMixin:
    async def _read_queens_backfill_entries(self, ctx):
        attachments = list(getattr(ctx.message, 'attachments', None) or [])
        json_atts = [
            a for a in attachments
            if getattr(a, 'filename', '').lower().endswith('.json')]
        if not json_atts:
            raise MinigameCogError(
                'Attach a history `.json` file (generated by '
                '`extra/queens_parse_messages.py`).')
        attachment = json_atts[0]
        size = int(getattr(attachment, 'size', 0) or 0)
        if size and size > _QUEENS_BACKFILL_MAX_BYTES:
            raise MinigameCogError(
                f'Attachment is {size} bytes — refusing anything over '
                f'{_QUEENS_BACKFILL_MAX_BYTES} bytes.')
        raw = await attachment.read()
        try:
            data = json.loads(raw.decode('utf-8'))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise MinigameCogError(f'Attachment is not valid JSON: {exc}.')
        if not isinstance(data, list):
            raise MinigameCogError(
                'JSON must be a list of result entries.')
        return data

    @staticmethod
    def _parse_queens_backfill_entry(game, entry):
        if not isinstance(entry, dict):
            raise ValueError('entry is not an object')
        linkedin_name = entry.get('linkedin_name', '')
        if not isinstance(linkedin_name, str) or not linkedin_name.strip():
            raise ValueError('entry has no LinkedIn name')
        linkedin_name = linkedin_name.strip()
        puzzle_number = int(entry['puzzle_number'])
        time_seconds = int(entry['time_seconds'])
        no_hints = bool(entry.get('no_hints', False))
        no_mistakes = bool(entry.get('no_mistakes', False))
        puzzle_date_iso = entry.get('puzzle_date')
        if puzzle_date_iso:
            puzzle_date = dt.date.fromisoformat(puzzle_date_iso)
            expected_date = game.linkedin.date_for_number(puzzle_number)
            if puzzle_date != expected_date:
                raise ValueError(
                    f'{game.display_name} puzzle #{puzzle_number} is for '
                    f'{expected_date.isoformat()}, not {puzzle_date.isoformat()}')
        else:
            puzzle_date = game.linkedin.date_for_number(puzzle_number)
        return (
            normalize_queens_name(linkedin_name),
            _QueensResolvedEntry(
                user_id=None,
                linkedin_name=linkedin_name,
                time_seconds=time_seconds,
                no_hints=no_hints,
                no_mistakes=no_mistakes,
            ),
            puzzle_date,
        )

    @staticmethod
    def _queens_backfill_raw_content(entry):
        return (
            'backfill from LinkedIn export '
            f'({entry.get("sent_at_utc", "")})'
        )

    def _existing_queens_source_rows(self, guild_id, game, normalized_name,
                                     source_rows_by_name):
        source_rows = source_rows_by_name.get(normalized_name)
        if source_rows is None:
            source_rows = list(
                cf_common.user_db.get_minigame_unresolved_results_for_name(
                    guild_id, game.name, normalized_name))
            source_rows_by_name[normalized_name] = source_rows
        return source_rows

    def _remember_queens_source_row(self, game, source_rows, normalized_name,
                                    parsed, puzzle_date):
        identity_key = self._queens_source_identity_key(
            game, normalized_name, puzzle_date)
        source_rows[:] = [
            row for row in source_rows
            if self._queens_source_identity_key(
                game, row.normalized_name, row.puzzle_date) != identity_key
        ]
        source_rows.append(SimpleNamespace(
            normalized_name=normalized_name,
            puzzle_number=game.linkedin.number_for_date(puzzle_date),
            puzzle_date=_queens_puzzle_date_text(puzzle_date),
            accuracy=100 if parsed.no_mistakes else 0,
            time_seconds=parsed.time_seconds,
            is_perfect=int(parsed.no_hints and parsed.no_mistakes),
        ))

    def _save_queens_backfill_source_entry(self, ctx, game, entry,
                                           normalized_name, parsed,
                                           puzzle_date, *, link=None,
                                           source_rows_by_name=None):
        if source_rows_by_name is None:
            source_rows_by_name = {}
        source_rows = self._existing_queens_source_rows(
            ctx.guild.id, game, normalized_name, source_rows_by_name)
        identity_key = self._queens_source_identity_key(
            game, normalized_name, puzzle_date)
        existing_rows = [
            row for row in source_rows
            if self._queens_source_identity_key(
                game, row.normalized_name, row.puzzle_date) == identity_key
        ]
        if any(self._legacy_queens_entry_matches_row(parsed, row)
               for row in existing_rows):
            return False

        if link is not None:
            parsed = parsed._replace(
                user_id=link.user_id,
                linkedin_name=link.external_name,
            )
        self._save_queens_external_result(
            ctx.guild.id, game, ctx.channel.id, parsed, puzzle_date,
            self._queens_backfill_raw_content(entry))
        self._remember_queens_source_row(
            game, source_rows, normalized_name, parsed, puzzle_date)
        return True

    def _save_queens_backfill_for_link(self, ctx, game, link, data):
        target_normalized = link.normalized_name
        matching = []
        for entry in data:
            if not isinstance(entry, dict):
                continue
            name = entry.get('linkedin_name', '')
            if not isinstance(name, str):
                continue
            if normalize_queens_name(name) == target_normalized:
                matching.append(entry)

        saved = 0
        skipped = 0
        malformed = 0
        source_rows_by_name = {}
        for entry in matching:
            try:
                normalized_name, parsed, puzzle_date = (
                    self._parse_queens_backfill_entry(game, entry))
            except (KeyError, TypeError, ValueError):
                malformed += 1
                continue

            if self._save_queens_backfill_source_entry(
                    ctx, game, entry, normalized_name, parsed, puzzle_date,
                    link=link, source_rows_by_name=source_rows_by_name):
                saved += 1
            else:
                skipped += 1

        return _QueensBackfillResult(
            link=link,
            matched=len(matching),
            saved=saved,
            skipped=skipped,
            malformed=malformed,
        )

    def _save_queens_backfill_all(self, ctx, game, data):
        links_by_name = {
            link.normalized_name: link
            for link in cf_common.user_db.get_minigame_player_links(
                ctx.guild.id, game.link_key)
            if not cf_common.user_db.is_minigame_banned(
                ctx.guild.id, game.name, link.user_id)
        }
        source_rows_by_name = {}
        saved = 0
        skipped = 0
        malformed = 0
        valid = 0
        registered_names = set()
        unresolved_names = set()
        for entry in data:
            try:
                normalized_name, parsed, puzzle_date = (
                    self._parse_queens_backfill_entry(game, entry))
            except (KeyError, TypeError, ValueError):
                malformed += 1
                continue
            valid += 1
            link = links_by_name.get(normalized_name)
            if link is None:
                unresolved_names.add(normalized_name)
            else:
                registered_names.add(normalized_name)
            if self._save_queens_backfill_source_entry(
                    ctx, game, entry, normalized_name, parsed, puzzle_date,
                    link=link, source_rows_by_name=source_rows_by_name):
                saved += 1
            else:
                skipped += 1
        return {
            'saved': saved,
            'skipped': skipped,
            'malformed': malformed,
            'valid': valid,
            'registered_names': registered_names,
            'unresolved_names': unresolved_names,
        }
